[
  {
    backdrop_path: "/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
    first_air_date: "1994-09-22",
    genre_ids: [35, 18],
    id: 1668,
    name: "Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Friends",
    overview:
      "Friends is an American television sitcom created by David Crane and Marta Kauffman, which aired on NBC from September 22, 1994, to May 6, 2004, lasting ten seasons. With an ensemble cast starring Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc, Matthew Perry and David Schwimmer, the show revolves around six friends in their 20s and 30s who live in Manhattan, New York City. The series was produced by Bright/Kauffman/Crane Productions, in association with Warner Bros. Television. The original executive producers were Kevin S. Bright, Kauffman, and Crane.",
    popularity: 162.553,
    poster_path: "/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
    vote_average: 8.4,
    vote_count: 5818,
    status: "Ended",
  },
  {
    backdrop_path: "/wIe1HL7oMNwyltsqqx2sCPwNl4w.jpg",
    first_air_date: "1984-10-09",
    genre_ids: [16, 10762],
    id: 2304,
    name: "Thomas & Friends",
    origin_country: ["GB"],
    original_language: "en",
    original_name: "Thomas & Friends",
    overview:
      "Thomas & Friends is a British children's television series, which had its first broadcast on the ITV network on 4 September 1984. It is based on The Railway Series of books by the Reverend Wilbert Awdry and his son, Christopher Awdry. These books deal with the adventures of a group of anthropomorphised locomotives and road vehicles who live on the fictional Island of Sodor. The books were based on stories Wilbert told to entertain his son, Christopher during his recovery from measles. From Series one to four, many of the stories are based on events from Awdry's personal experience.",
    popularity: 47.804,
    poster_path: "/s8RtAklJqHo6iMtKz1FIVBm92R2.jpg",
    vote_average: 6.5,
    vote_count: 71,
    status: "Returning Series",
  },
  {
    backdrop_path: "/2FiRbfbmXN2DSHAcuHRtv9QJwnD.jpg",
    first_air_date: "1999-12-24",
    genre_ids: [16, 35, 10765],
    id: 1126,
    name: "Happy Tree Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Happy Tree Friends",
    overview:
      "This action and adventure comedy is drawn in simple appearance and combines cute forest animals with extreme graphic violence. Each episode revolves around the characters enduring accidental events of bloodshed, pain, dismemberment and/or death.",
    popularity: 25.782,
    poster_path: "/2rYqJg1OzaDlc5kiBK4IdgrELMf.jpg",
    vote_average: 7.9,
    vote_count: 453,
    status: "Canceled",
  },
  {
    backdrop_path: "/4TK1IREtfd7Ki8JWfwR1WahO5IP.jpg",
    first_air_date: "1988-09-17",
    genre_ids: [16, 35],
    id: 4606,
    name: "Garfield and Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Garfield and Friends",
    overview:
      "The animated stories of Garfield the cat, Odie the dog, their owner Jon and the trouble they get into. And also Orson the Pig and his adventures on a farm with his fellow farm animals.",
    popularity: 33.957,
    poster_path: "/3HyTfZ9sSCoZPYrYHMffhRVm3Af.jpg",
    vote_average: 7.3,
    vote_count: 272,
    status: "Ended",
  },
  {
    backdrop_path: "/ea2Bw6064VpAE7FsLFBlSIb6Qcr.jpg",
    first_air_date: "1992-04-06",
    genre_ids: [35, 10751, 10762],
    id: 4887,
    name: "Barney & Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Barney & Friends",
    overview:
      "Barney & Friends is an American children's television series aimed at children from ages 2 to 5. The series, which first aired on April 6, 1992, features the title character Barney, a purple anthropomorphic Tyrannosaurus rex who conveys educational messages through songs and small dance routines with a friendly, optimistic attitude.\n\nNew episodes have not been produced since 2009; however reruns continue to air on various PBS stations.",
    popularity: 15.519,
    poster_path: "/ijt54PA1pZ2ae68ODBk3vfWSK0e.jpg",
    vote_average: 4.9,
    vote_count: 52,
    status: "Ended",
  },
  {
    backdrop_path: "/mdlhw5MHghUwNQZE860xHGEoi2T.jpg",
    first_air_date: "2015-06-26",
    genre_ids: [35, 10751, 10765],
    id: 62783,
    name: "Best Friends Whenever",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Best Friends Whenever",
    overview:
      "When their aspiring scientist friend Barry's invention goes awry, best friends Shelby and Cyd gain the power to leap forward and backward in time whenever they want – and sometimes when they don't. Now, they experience the twists and turns of friendship and must decide between fixing mistakes in the past or catching a glimpse of the future. While Barry and his assistant, Naldo, try to figure out how to replicate time travel for themselves, Cyd and Shelby use their newfound power to navigate high school life and Shelby's mischievous twin brothers, Bret and Chet.",
    popularity: 22.109,
    poster_path: "/euWwJsDLPzfPny96UrbD13XOFSz.jpg",
    vote_average: 8.4,
    vote_count: 66,
    status: "Canceled",
  },
  {
    backdrop_path: "/rocStLc3VNlVTg5p7TY0uqUcGCw.jpg",
    first_air_date: "2004-08-13",
    genre_ids: [10751, 16, 10765, 35],
    id: 1720,
    name: "Foster's Home for Imaginary Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Foster's Home for Imaginary Friends",
    overview:
      "Children who create imaginary friends usually take care of them until they are 7-8 years old. Imaginary friends, left on their own after this event, continue to live in this home founded by old Madam Foster.",
    popularity: 40.935,
    poster_path: "/aerZJVODYwji4BnyWrHFmF3JxhX.jpg",
    vote_average: 7.9,
    vote_count: 371,
    status: "Ended",
  },
  {
    backdrop_path: "/yLLRJwHlRwADEojNwVhqAxSH8hh.jpg",
    first_air_date: "2014-12-23",
    genre_ids: [16, 35, 10762],
    id: 81425,
    name: "Talking Tom and Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Talking Tom and Friends",
    overview:
      "Armed with technological gear, great ideas and an unfailing sense of humour, Talking Tom and his friends are on a mission to reach stardom at all costs.",
    popularity: 22.28,
    poster_path: "/fVeSFv892YdLcvftJAZPSDBTpyp.jpg",
    vote_average: 8.3,
    vote_count: 8,
    status: "Returning Series",
  },
  {
    backdrop_path: "/dZH60ElHGGdMUbSDstDqGlTz6dV.jpg",
    first_air_date: "2021-08-06",
    genre_ids: [10762, 16],
    id: 127635,
    name: "Marvel's Spidey and His Amazing Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Marvel's Spidey and His Amazing Friends",
    overview:
      "Follow Peter Parker, Gwen Stacy and Miles Morales and their adventures as the young heroes team up with Hulk, Ms. Marvel and Black Panther to defeat foes like Rhino, Doc Ock and Green Goblin and learn that teamwork is the best way to save the day.",
    popularity: 36.226,
    poster_path: "/dA4S18rnLx4sWW8agmLLKUvRM7n.jpg",
    vote_average: 7.3,
    vote_count: 203,
    status: "Returning Series",
  },
  {
    backdrop_path: "/cL8MPDoy00GtVnUvhhNJXBcreNU.jpg",
    first_air_date: "1981-09-12",
    genre_ids: [10759, 16, 10751, 10765],
    id: 1269,
    name: "Spider-Man and His Amazing Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Spider-Man and His Amazing Friends",
    overview:
      "Spider-Man and His Amazing Friends is an American animated television series produced by Marvel Productions starring established Marvel Comics characters Spider-Man and Iceman and an original character, Firestar. As a trio called the Spider-Friends, they fought against various villains.",
    popularity: 34.258,
    poster_path: "/4GjLlD5u8LtkF5XJ75FlPW16fHG.jpg",
    vote_average: 7.5,
    vote_count: 191,
    status: "Ended",
  },
  {
    backdrop_path: "/4Pf3jV52oCzGen4aWMl897v86wl.jpg",
    first_air_date: "2018-03-16",
    genre_ids: [16, 10762],
    id: 87547,
    name: "LEGO Friends: Girls on a Mission",
    origin_country: [],
    original_language: "en",
    original_name: "LEGO Friends: Girls on a Mission",
    overview:
      "Meet Andrea, Mia, Emma, Olivia and Stephanie. They're five best friends. And they're on a heroic mission: to save Heartlake City from wily swindlers.",
    popularity: 12.24,
    poster_path: "/ucWzrdR7Ac4WVzx6FMFRNukNUqe.jpg",
    vote_average: 7.7,
    vote_count: 11,
    status: "Returning Series",
  },
  {
    backdrop_path: "/qjHTkQ3QUlw6sxkIhugqNYsRJnR.jpg",
    first_air_date: "2020-04-01",
    genre_ids: [16, 35],
    id: 126506,
    name: "Smiling Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Smiling Friends",
    overview:
      "Smiling Friends Inc. is a small company whose main purpose is to bring happiness and make people smile. The series follows the day-to-day lives and misadventures of its representatives, the lazy, cynical Charlie, and the cheerful, optimistic Pim, as they try to cheer up and comfort the troubled people who call their company's hotline. They receive seemingly simple requests but the jobs turn out to be more complicated than they seem, making it difficult to bring happiness to the world.",
    popularity: 10.445,
    poster_path: "/xAJIdD5u9lo1RezhfcSq6s1jH2A.jpg",
    vote_average: 8.1,
    vote_count: 29,
    status: "Returning Series",
  },
  {
    backdrop_path: "/oU1MEa06XQSMA8i4dBnhR0oXfSK.jpg",
    first_air_date: "1973-09-08",
    genre_ids: [16, 10765],
    id: 936,
    name: "Super Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Super Friends",
    overview:
      "The most powerful heroes ever--Superman, Wonder Woman, Aquaman, Batman and Robin--join forces with teenagers Wendy and Marvin and their dog, Marvel the Wonderdog, to defend justice and guard the innocent.",
    popularity: 9.21,
    poster_path: "/5U05cOQ64hpRxhhvGSj3cGTx5zm.jpg",
    vote_average: 7.7,
    vote_count: 98,
    status: "Ended",
  },
  {
    backdrop_path: "/AcSHFicz81rDmD73kCkWccszWBQ.jpg",
    first_air_date: "2011-08-05",
    genre_ids: [18, 35],
    id: 9777,
    name: "Friends with Benefits",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Friends with Benefits",
    overview:
      "Revolving around a group of twentysomething singles as they navigate the difficult, sometimes rewarding, often confusing world of dating. Loyal and devoted to one another, these friends are never too busy to help a member of the group who might be in need. In fact, their companionship often extends into a more intimate setting - the bedroom.",
    popularity: 9.568,
    poster_path: "/kqHYN5Ei3RyNWcHabLPRGW7hT6T.jpg",
    vote_average: 6.2,
    vote_count: 20,
    status: "Canceled",
  },
  {
    backdrop_path: "/njylQZh5gvVEVBq66B7Avi5OKIl.jpg",
    first_air_date: "2007-05-12",
    genre_ids: [10762, 16, 18, 9648, 10759],
    id: 3527,
    name: "My Friends Tigger & Pooh",
    origin_country: ["US"],
    original_language: "en",
    original_name: "My Friends Tigger & Pooh",
    overview:
      "Pooh, Tigger, and friends from the Hundred Acre Wood welcome new neighbors — an adorable six-year-old girl named Darby and her puppy, Buster. With the help of adventurous super sleuths Tigger and Pooh, every episode revolves around the solving of a mystery and an interactive curriculum that encourages viewers to help them out.",
    popularity: 14.951,
    poster_path: "/pjFdWwr36A5ZO8K5W5NuPRS7Bil.jpg",
    vote_average: 6.7,
    vote_count: 11,
    status: "Ended",
  },
  {
    backdrop_path: "/kmZcWzvyaNDwEBiukmvrB2iDLid.jpg",
    first_air_date: "2017-07-14",
    genre_ids: [35],
    id: 71890,
    name: "Friends from College",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Friends from College",
    overview:
      "Twenty years after graduation, a tight-knit group of college friends reconnects and discovers that love hasn't gotten easier with age.",
    popularity: 8.951,
    poster_path: "/38HzAmLPNALw0fSdZ7rMH0EymqC.jpg",
    vote_average: 6.5,
    vote_count: 54,
    status: "Canceled",
  },
  {
    backdrop_path: "/zUw5IRkHZnZ1arE68UHyRAQ6Ox6.jpg",
    first_air_date: "2022-05-15",
    genre_ids: [18],
    id: 99747,
    name: "Conversations with Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Conversations with Friends",
    overview:
      "Two college students, Frances and Bobbi, forge a strange and unexpected relationship with a married couple.",
    popularity: 6.531,
    poster_path: "/kk6kXltSgeAA1yWiRaZ1sOexm1V.jpg",
    vote_average: 8.4,
    vote_count: 25,
    status: "Ended",
  },
  {
    backdrop_path: "/cpo5hw44VlMhLhzDpWRbDCBcimb.jpg",
    first_air_date: "2016-03-04",
    genre_ids: [16, 10762, 10751],
    id: 70779,
    name: "LEGO Friends: The Power of Friendship",
    origin_country: ["US"],
    original_language: "en",
    original_name: "LEGO Friends: The Power of Friendship",
    overview: "",
    popularity: 7.74,
    poster_path: "/7yKAIvZwElfeI3wjtRIMDl2ySHp.jpg",
    vote_average: 7.7,
    vote_count: 99,
    status: "Ended",
  },
  {
    backdrop_path: "/vWgrKicr8j51NaNrH9VzpgrRys6.jpg",
    first_air_date: "2018-07-16",
    genre_ids: [16, 35],
    id: 81553,
    name: "Peepoodo & The Super Fuck Friends",
    origin_country: ["FR"],
    original_language: "fr",
    original_name: "Peepoodo & The Super Fuck Friends",
    overview:
      "An educative series for children over 18 years old that explores sexuality without taboos and in all its forms, including dicks and nipples. A positive sexuality, that is unrestrained and totally ignores prejudices… culminating into one single message: tolerance.",
    popularity: 9.518,
    poster_path: "/hJnvyzMP4md3f1Xx0wumftXCC6l.jpg",
    vote_average: 9,
    vote_count: 5,
    status: "Returning Series",
  },
  {
    backdrop_path: "/sXVvrO5PzMLdmbB0dmQ5UbAfgy9.jpg",
    first_air_date: "2012-05-05",
    genre_ids: [16, 10762],
    id: 68820,
    name: "LEGO Friends",
    origin_country: ["US"],
    original_language: "en",
    original_name: "LEGO Friends",
    overview: "Five Best Friends Go on Many Fun Lego adventures.",
    popularity: 2.992,
    poster_path: "/b855aXC8IWQQq6TmHuAwlpmQUVv.jpg",
    vote_average: 5,
    vote_count: 1,
    status: "Returning Series",
  },
];
